[build]
  publish = "src/test_site/"
  functions = "functions/dist"
  command = "npm run build"

  [[redirects]]
  from = "/api"
  to = "https://futuregerald.app/.netlify/functions/showheaders"
  status = 200
  force = true
  signed = "TESTING"