[build]
  publish = "src/test_site/"
  functions = "functions/dist"
  command = "yarn --version && npm run build"

[build.environment]
  YARN_VERSION = '1.9.4'

  [[redirects]]
  from = "/api"
  to = "https://futuregerald-requestbin.herokuapp.com/tw63n2tw"
  status = 200
  force = true
  signed = "TESTING"

  